### ISSUE TITLE
Sample configurations for "netprobe" tap and policy

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#490]
The purpose of this ticket is to discuss how to structure the new `netprobe` tap and handler. Here are a few concepts to keep in mind in reviewing this:
-  the `netprobe` _tap_ provides the basic facilities to run network tests, but should only include host specific configuration settings and default configuration overrides
- the `netprobe` _input_ is where the network tests are defined and configured, as well as any default configuration overrides
- the `netprobe` _handler_ is where the metrics that are to be measured and collected are configured

Here is a sample configuration for the `netprobe` tap:
```yaml
version: "1.0"

visor:
  taps:
    default_netprobe:
      input_type: netprobe
      config:
        maximum_concurrent_tests: 10
        ip_source_binding: 127.0.0.1
      tags:
        virtual: true
        vhost: 1 
```

Here is a sample policy for the `netprobe` input and handler:
```yaml
version: "1.0"

visor:
  policies:
    basic_ping_policy:
      kind: collection
      description: "basic PING netprobe policy"
      input:
        tap: default_netprobe
        input_type: netprobe
        config:
          test_type: ping
          interval_msec: 2000
          timeout_msec: 1000
          packets_per_test: 10
          packets_interval_msec: 25
          packet_payload_size: 56
          disable_scout_packet: false
          disable_integrity_check: false
          targets:
            test_1_name:
              target: foo.bar
            test_2_name:
              target: 10.0.0.1
              tos: EF
      handlers:
        config:
          num_periods: 2 #default is 5
        modules:
          default_ping:
            type: netprobe
            config:
              latency_units: msec
            metric_groups:
              enable:
                - quantiles
                - dns_resolution
              disable:
                - jitter
```
