### ISSUE TITLE
Exploratory tests using pktvisor + netprobe input

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#522]
Explore tests considering pktvisor + netprobe

The result of this will be:

- description of new test scenarios
- validations or bugs

**Comment by manrodrigues** [comment]
I'm considering the netprobe issue (https://github.com/ns1labs/pktvisor/issues/490)..

**Comment by manrodrigues** [comment]
agent.yaml:

```
version: "1.0"

visor:
  config:
    verbose: true
  # optionally define taps
  taps:
    default_netprobe:
      input_type: netprobe
      config:
        maximum_concurrent_tests: 10
        ip_source_binding: 127.0.0.1
      tags:
        virtual: true
        vhost: 1 
  policies:
    basic_ping_policy:
      kind: collection
      description: "basic PING netprobe policy"
      input:
        tap: default_netprobe
        input_type: netprobe
        config:
          test_type: ping
          interval_msec: 2000
          timeout_msec: 1000
          packets_per_test: 1
          packets_interval_msec: 10
          packet_payload_size: 56
          disable_scout_packet: false
          disable_integrity_check: false
          targets:
            test_1_name:
              target: https://stg.orb.live
            test_2_name:
              target: 10.0.0.1
              tos: EF
      handlers:
        config:
          num_periods: 2 #default is 5
        modules:
          default_ping:
            type: netprobe
            config:
              latency_units: msec
            metric_groups:
              enable:
                - quantiles
                - dns_resolution
              disable:
                - jitter
```

**Comment by manrodrigues** [comment]
Configs:

I tried `timeout_msec` with value higher than `interval_msec` and no error was raised.
For example:
```
          interval_msec: 10
          timeout_msec: 1000
```

If the `interval_msec` determines after how many milliseconds another test will be started, I don't think the timeout can take a value greater than the interval.
Unless the interval starts to be counted after the timeout or response of the current test.

So, that's my question:

- Does the `interval_msec` determine how long after the start of the current test another test will start or how long after the end of the current test?

**Comment by manrodrigues** [comment]
Configs:

- Should we have a minimum for the `interval_msec`?
I'm wondering if using very small values ​​(1 msec, for example) can be like an attack on some URL.

**Comment by manrodrigues** [comment]
Configs:

- the product of `packets_per_test` and `packets_interval_msec`(`packets_per_test * packets_interval_msec`) is the minimum duration time of a complete test. This value shouldn't be able to be greater than the timeout_msec, because I haven't even finished sending the packets I want yet.

I tried using values greater and no error was raised.

```
          timeout_msec: 1000
          packets_per_test: 10
          packets_interval_msec: 200
```

Note that to send all the 10 packets with 200 msec of interval I'll need 2000 msec.. but the timeout is 1000.

Should we have limit it?

**Comment by manrodrigues** [comment]
Configs:

We need to limit `packet_payload_size` with a maximum value.. because I tried with a big value and pktvisor ends with error:

`packet_payload_size: 56000000000`

[_awesome_wing_logs.txt](https://github.com/ns1labs/pktvisor/files/9940824/_awesome_wing_logs.txt)

When I used  `packet_payload_size: 5600000000` pktvisor also ends:

[_pensive_almeida_logs.txt](https://github.com/ns1labs/pktvisor/files/9940832/_pensive_almeida_logs.txt)


Another interesting note about it:

i'm using `packet_payload_size: 560000000` and pktvisor not ends with an error, but I cannot see "attempts" on the buckets and I don't know why it means:


```
{
    "basic_ping_policy": {
        "basic_ping_policy-default_netprobe-default_ping": {
            "netprobe": {
                "period": {
                    "length": 86,
                    "start_ts": 1667583541
                }
            }
        }
    },
    "default_netprobe-f4385989695f5dd7-resources": {
        "default_netprobe-f4385989695f5dd7-resources": {
            "input_resources": {
                "deep_samples": 1,
                "event_rate": {
                    "live": 0,
                    "p50": 0,
                    "p90": 0,
                    "p95": 0,
                    "p99": 1
                },
                "handler_count": 1,
                "period": {
                    "length": 86,
                    "start_ts": 1667583541
                },
                "policy_count": 1,
                "total": 1
            }
        }
    }
}
```

**Comment by manrodrigues** [comment]
Configs:

I'm able to run two "target" in the same target.. is it ok? 

```    
      targets:
            test_1_name:
              target: 108.158.147.91
              target: 142.251.128.78
```
