### ISSUE TITLE
Netprobe: Success rate for ping test is greater than 1 at some times

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#561]
Observed success rate for ping tests (successes/attempts) is greater than 1 at some times. 

![MicrosoftTeams-image (8).png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/755d4d2f-e304-4430-b7ae-2a4708075ca5)

Looking to the data without considering the average, we see this kind of behavior:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/00d2c28f-7a9b-4806-bee0-b525cf134c82)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/de5320b5-3d44-454c-8580-63902494f0a8)

It seems that the success of a previous attempt adds up to the next point.. this generates a strange data.. I'm opening this card so that you can look and see if there is something to be done so that the metric is always relative to the same test.. how many successes they had for X amount of attempts on this test.

I'm using this policy:

```
handlers:
  modules:
    default_netprobe:
      type: netprobe
      metric_groups:
        enable:
          - counters
          - quantiles
input:
  tap: default_netprobe
  input_type: netprobe
  config:
    test_type: ping
    packets_per_test: 5
    interval_msec: 2000
    timeout_msec: 1000
    packets_interval_msec: 10
    packet_payload_size: 56
    targets:
      www.google.com:
        target: www.google.com
      'orb live':
        target: orb.live
      orb_community:
        target: orb.community       
kind: collection
```
